---

- name: 'Mod pattern 1'
  konono.easyconf.ezconf:
    src: '{{ playbook_dir }}/tests/test.yml'
    key: 'config.person[-1]'
    value: { "name": "yuri", "gender": "female", "age": 21}
    state: 'present'

- name: 'Mod pattern 2'
  konono.easyconf.ezconf:
    src: '{{ playbook_dir }}/tests/test.yml'
    key: 'config.fruits'
    value: 'orange'
    state: 'present'

- name: 'Mod pattern 3'
  konono.easyconf.ezconf:
    src: '{{ playbook_dir }}/tests/test.yml'
    key: 'my.favorite.whiskey'
    value: "macallan"
    state: 'present'
